In [ ]:
#SEISMIC BUMPS
!pip install imblearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv("seismic-bump.csv")
data.head()

id seismic seismoacoustic shift  genergy  gpuls  gdenergy  gdpuls ghazard  \
0   1       a              a     N    15180     48       -72     -72       a   
1   2       a              a     N    14720     33       -70     -79       a   
2   3       a              a     N     8050     30       -81     -78       a   
3   4       a              a     N    28820    171       -23      40       a   
4   5       a              a     N    12640     57       -63     -52       a   

   nbumps  nbumps2  nbumps3  nbumps4  nbumps5  nbumps6  nbumps7  nbumps89  \
0       0        0        0        0        0        0        0         0   
1       1        0        1        0        0        0        0         0   
2       0        0        0        0        0        0        0         0   
3       1        0        1        0        0        0        0         0   
4       0        0        0        0        0        0        0         0   

   energy  maxenergy  class  
0       0          0      0  
1    2000       2000      0  
2       0          0      0  
3    3000       3000      0  
4       0          0      0

In [ ]:
data.shape

(2584, 20)

In [ ]:
data['class'].value_counts()

0    2414
1     170
Name: class, dtype: int64

In [ ]:
data['seismic'].unique()

array(['a', 'b'], dtype=object)

In [ ]:
data['seismic'].value_counts()

a    1682
b     902
Name: seismic, dtype: int64

In [ ]:
data['seismoacoustic'].unique()

array(['a', 'b', 'c'], dtype=object)

In [ ]:
data['seismoacoustic'].value_counts()

a    1580
b     956
c      48
Name: seismoacoustic, dtype: int64

In [ ]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
data['seismic']= label_encoder.fit_transform(data['seismic']) 
  
data['seismic'].unique() 

array([0, 1])

In [ ]:
data['seismic']

0       0
1       0
2       0
3       0
4       0
       ..
2579    1
2580    1
2581    1
2582    0
2583    0
Name: seismic, Length: 2584, dtype: int64

In [ ]:
data['seismoacoustic']= label_encoder.fit_transform(data['seismoacoustic']) 
  
data['seismoacoustic'].unique() 

array([0, 1, 2])

In [ ]:
data['ghazard']= label_encoder.fit_transform(data['ghazard']) 
  
data['ghazard'].unique() 

array([0, 1, 2])

In [ ]:
data['shift']= label_encoder.fit_transform(data['shift']) 
  
data['shift'].unique() 

array([0, 1])

In [ ]:
data.head()

id  seismic  seismoacoustic  shift  genergy  gpuls  gdenergy  gdpuls  \
0   1        0               0      0    15180     48       -72     -72   
1   2        0               0      0    14720     33       -70     -79   
2   3        0               0      0     8050     30       -81     -78   
3   4        0               0      0    28820    171       -23      40   
4   5        0               0      0    12640     57       -63     -52   

   ghazard  nbumps  nbumps2  nbumps3  nbumps4  nbumps5  nbumps6  nbumps7  \
0        0       0        0        0        0        0        0        0   
1        0       1        0        1        0        0        0        0   
2        0       0        0        0        0        0        0        0   
3        0       1        0        1        0        0        0        0   
4        0       0        0        0        0        0        0        0   

   nbumps89  energy  maxenergy  class  
0         0       0          0      0  
1         0    2000       2000      0  
2         0       0          0      0  
3         0    3000       3000      0  
4         0       0          0      0

In [ ]:
X = data.drop('class', axis = 1)
y= data['class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
A_train, A_test, B_train, B_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
!pip install smote_variants

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#CLUSTERSMOTE
import smote_variants as sv
oversample=sv.MulticlassOversampling(oversampler='distance_SMOTE',
                                      oversampler_params={'random_state': 5})
X_train,y_train=oversample.sample(X_train,y_train)



2023-04-02 04:29:21,610:INFO:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
INFO:smote_variants:MulticlassOversampling: Running multiclass oversampling with strategy eq_1_vs_many_successive
2023-04-02 04:29:21,620:INFO:MulticlassOversampling: Sampling minority class with label: 1
INFO:smote_variants:MulticlassOversampling: Sampling minority class with label: 1
2023-04-02 04:29:21,632:INFO:distance_SMOTE: Running sampling via ('distance_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 2, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': 5, 'class_name': 'distance_SMOTE'}")
INFO:smote_variants:distance_SMOTE: Running sampling via ('distance_SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 2, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}

In [ ]:
#clusterSmote logistic 
from sklearn.linear_model import LogisticRegression 
data_Check = LogisticRegression()
data_Check.fit(X_train, y_train)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  73.88781431334623 %


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [ ]:
#cluster smote random forest
from sklearn.ensemble import RandomForestClassifier 
data_Check= RandomForestClassifier(random_state=1) 
data_Check.fit(X_train, y_train)
y_pred = data_Check.predict(X_test) 
correct = (y_pred == y_test).sum() 
accuracy = correct/len(y_test)*100 
print("accuracy =", accuracy, "%")

accuracy = 93.03675048355899 %


In [ ]:
#cluster smote decision tree
from sklearn.tree import DecisionTreeClassifier  
data_classifier = DecisionTreeClassifier()  
data_classifier.fit(X_train, y_train) 
y_pred = data_classifier.predict(X_test)


correct = (y_pred==y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  90.52224371373308 %


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


In [ ]:
# Import necessary libraries
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import KMeansSMOTE
from collections import Counter

# Split the data into training and testing sets
A_train, A_test, B_train, B_test=train_test_split(X,y,test_size=0.2, random_state=63)

# Create an instance of KMeansSMOTE
kmeans_smote = KMeansSMOTE(
    sampling_strategy='auto', # resample all classes
    cluster_balance_threshold=0.1, # lower the cluster balance threshold
    random_state=42,
    k_neighbors=5, # number of nearest neighbors to use
    n_jobs=-1 # use all available CPU cores
)

# Fit and resample the training data
X_resampled, y_resampled = kmeans_smote.fit_resample(A_train, B_train)

# Print the class distribution before and after resampling
print('Class distribution before resampling:', Counter(y_train))
print('Class distribution after resampling:', Counter(y_resampled))


/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Class distribution before resampling: Counter({0: 1934, 1: 133})
Class distribution after resampling: Counter({1: 1930, 0: 1929})


In [ ]:
#KmeansSmote logistic
from sklearn.linear_model import LogisticRegression 
data_Check = LogisticRegression()
data_Check.fit(A_train, B_train)
y_pred_km= data_Check.predict(A_test)
correct = (y_pred_km == B_test).sum()
accuracy = correct/len(B_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  93.61702127659575 %


In [ ]:
#kmeans smote random forest
from sklearn.ensemble import RandomForestClassifier 
data_Check= RandomForestClassifier(random_state=1) 
data_Check.fit(A_train, B_train)
y_pred = data_Check.predict(A_test) 
correct = (y_pred == B_test).sum() 
accuracy = correct/len(B_test)*100 
print("accuracy =", accuracy, "%")

accuracy = 93.81044487427465 %


In [ ]:
#kmeans smote decision tree
from sklearn.tree import DecisionTreeClassifier  
data_classifier = DecisionTreeClassifier()  
data_classifier.fit(A_train, B_train) 
y_pred = data_classifier.predict(A_test)


correct = (y_pred==B_test).sum()
accuracy = correct/len(B_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  88.39458413926499 %
