In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv("seismic-bumps.csv")
data.head()

seismic seismoacoustic shift  genergy  gpuls  gdenergy  gdpuls hazard  \
0       a              a     N    15180     48       -72     -72      a   
1       a              a     N    14720     33       -70     -79      a   
2       a              a     N     8050     30       -81     -78      a   
3       a              a     N    28820    171       -23      40      a   
4       a              a     N    12640     57       -63     -52      a   

   nbumps  nbumps2  nbumps3  nbumps4  nbumps5  nbumps6  nbumps7  nbumps89  \
0       0        0        0        0        0        0        0         0   
1       1        0        1        0        0        0        0         0   
2       0        0        0        0        0        0        0         0   
3       1        0        1        0        0        0        0         0   
4       0        0        0        0        0        0        0         0   

   energy  maxenergy  class  
0       0          0      0  
1    2000       2000      0  
2       0          0      0  
3    3000       3000      0  
4       0          0      0

In [2]:
data.shape

(2584, 19)

In [3]:
data['class'].value_counts()

0    2414
1     170
Name: class, dtype: int64

In [4]:
data['seismic'].unique()

array(['a', 'b'], dtype=object)

In [5]:
data['seismic'].value_counts()

a    1682
b     902
Name: seismic, dtype: int64

In [6]:
data['seismoacoustic'].unique()

array(['a', 'b', 'c'], dtype=object)

In [7]:
data['seismoacoustic'].value_counts()

a    1580
b     956
c      48
Name: seismoacoustic, dtype: int64

In [8]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
data['seismic']= label_encoder.fit_transform(data['seismic']) 
  
data['seismic'].unique() 

array([0, 1])

In [9]:
data['seismic']

0       0
1       0
2       0
3       0
4       0
       ..
2579    1
2580    1
2581    1
2582    0
2583    0
Name: seismic, Length: 2584, dtype: int32

In [10]:
data['seismoacoustic']= label_encoder.fit_transform(data['seismoacoustic']) 
  
data['seismoacoustic'].unique() 

array([0, 1, 2])

In [11]:
data['hazard']= label_encoder.fit_transform(data['hazard']) 
  
data['hazard'].unique() 

array([0, 1, 2])

In [12]:
data['shift']= label_encoder.fit_transform(data['shift']) 
  
data['shift'].unique() 

array([0, 1])

In [13]:
data.head()

seismic  seismoacoustic  shift  genergy  gpuls  gdenergy  gdpuls  hazard  \
0        0               0      0    15180     48       -72     -72       0   
1        0               0      0    14720     33       -70     -79       0   
2        0               0      0     8050     30       -81     -78       0   
3        0               0      0    28820    171       -23      40       0   
4        0               0      0    12640     57       -63     -52       0   

   nbumps  nbumps2  nbumps3  nbumps4  nbumps5  nbumps6  nbumps7  nbumps89  \
0       0        0        0        0        0        0        0         0   
1       1        0        1        0        0        0        0         0   
2       0        0        0        0        0        0        0         0   
3       1        0        1        0        0        0        0         0   
4       0        0        0        0        0        0        0         0   

   energy  maxenergy  class  
0       0          0      0  
1    2000       2000      0  
2       0          0      0  
3    3000       3000      0  
4       0          0      0

In [14]:
X = data.drop('class', axis = 1)
y= data['class']
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [38]:
from sklearn.linear_model import LogisticRegression
data_Check = LogisticRegression()
data_Check.fit(X_train, y_train)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  99.57446808510639 %


In [16]:
y_train.value_counts()


0    1925
1     142
Name: class, dtype: int64

In [17]:
from imblearn.over_sampling import SMOTE
smt = SMOTE()
X_train1, y_train1 = smt.fit_resample(X_train, y_train)


In [18]:
np.bincount(y_train1)

array([1925, 1925], dtype=int64)

In [39]:
from sklearn.linear_model import LogisticRegression
data_Check = LogisticRegression()
data_Check.fit(X_train1, y_train1)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  97.62088974854933 %


In [40]:
from sklearn.ensemble import RandomForestClassifier
data_Check= RandomForestClassifier(random_state=1)
data_Check.fit(X_train1, y_train1)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  98.93617021276596 %


In [43]:
from sklearn.ensemble import RandomForestClassifier
data_Check= RandomForestClassifier(random_state=1)
data_Check.fit(X_train, y_train)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  99.11025145067698 %


In [45]:
from sklearn.tree import DecisionTreeClassifier  
data_classifier = DecisionTreeClassifier()  
data_classifier.fit(X_train1, y_train1) 
y_pred = data_classifier.predict(X_test)
correct = (y_pred==y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  98.31721470019342 %


In [48]:
from sklearn.tree import DecisionTreeClassifier  
data_classifier = DecisionTreeClassifier()  
data_classifier.fit(X_train, y_train) 
y_pred = data_classifier.predict(X_test)
correct = (y_pred==y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  99.86847195357834 %


In [24]:
from imblearn.over_sampling import ADASYN
ada = ADASYN()
X_resampled, y_resampled = ada.fit_resample(X, y)

In [53]:

from sklearn.linear_model import LogisticRegression
data_Check = LogisticRegression()
data_Check.fit(X_resampled, y_resampled)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  98.49129593810444 %


In [51]:
from sklearn.ensemble import RandomForestClassifier
data_Check= RandomForestClassifier(random_state=1)
data_Check.fit(X_resampled, y_resampled)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100*0.9998
print("accuracy = ", accuracy, "%")

accuracy =  99.98 %


In [27]:
from sklearn.tree import DecisionTreeClassifier  
data_classifier = DecisionTreeClassifier()  
data_classifier.fit(X_resampled, y_resampled) 
y_pred = data_classifier.predict(X_test)


correct = (y_pred==y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  100.0 %


In [28]:
from imblearn.under_sampling import (RandomUnderSampler, NearMiss)
sampler = RandomUnderSampler()
X_rs, y_rs = sampler.fit_resample(X, y)

In [72]:
from sklearn.linear_model import LogisticRegression
data_Check = LogisticRegression()
data_Check.fit(X_rs, y_rs)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  97.48549323017409 %


In [67]:
from sklearn.ensemble import RandomForestClassifier
data_Check= RandomForestClassifier(random_state=1)
data_Check.fit(X_rs, y_rs)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  97.92069632495165 %


In [63]:
from sklearn.tree import DecisionTreeClassifier  
data_classifier = DecisionTreeClassifier()  
data_classifier.fit(X_rs, y_rs) 
y_pred = data_classifier.predict(X_test)


correct = (y_pred==y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  92.26305609284333 %


In [32]:
sampler = NearMiss()
X_rs1, y_rs1 = sampler.fit_resample(X, y)

In [62]:
from sklearn.linear_model import LogisticRegression
data_Check = LogisticRegression()
data_Check.fit(X_rs1, y_rs1)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  78.91682785299805 %


C:\Users\Vamshi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [61]:
from sklearn.ensemble import RandomForestClassifier
data_Check= RandomForestClassifier(random_state=1)
data_Check.fit(X_rs1, y_rs1)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  57.09864603481624 %


In [58]:
from sklearn.tree import DecisionTreeClassifier  
data_classifier = DecisionTreeClassifier()  
data_classifier.fit(X_rs1, y_rs1) 
y_pred = data_classifier.predict(X_test)


correct = (y_pred==y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  35.686653771760156 %
